on:
 push:
  branches: 
   - main

jobs:
 deploy:
  runs-on: Ubuntu-latest
  name: Deploy_api_file
  steps: 
   - name: Checkout-code
     uses: actions/Checkout@V2
   - name: Login to Dockerhub
     uses: docker/login-action@v1
     with: 
      username: ${{secrets.DOCKERUSERNAME}}
      password: ${{secrets.DOCKERPASSWORD}}
   - name: build, tag and push
     env: 
      DOCKERHUBUSERNAME: ${{secrets.DOCKERUSERNAME}}
      IMAGENAME: api-image
     run: 
      docker buildx build --platform linux/amd64 -t $DOCKERHUBUSERNAME/$IMAGENAME --load /app
      docker push $DOCKERHUBUSERNAME/$IMAGENAME:latest
